---
title: "Desafio2"
author: "Aline Ramos"
date: "28/04/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r knitt, message=FALSE}
#####Letraa 
w1 <- c(10,11,12,13,14,15,16,17,18,19,20,21,22)
pw1 <- c(("1/35"),("1/35"),("2/35"),("3/35"),("4/35"),("4/35"),("5/35"),
         "4/35","4/35","3/35","2/35","1/35","1/35")
Probabilidade <- c((1/35),(1/35),(2/35),(3/35),(4/35),(4/35),(5/35),
                   4/35,4/35,3/35,2/35,1/35,1/35)
final1 <- rbind(w1,Probabilidade)


ws <- w1
final1 <- plot(ws,Probabilidade)
library(ggplot2)
jpeg("method1_test.jpg")
p <- ggplot(final1, aes(ws,Probabilidade))
p + geom_linerange(aes(ymin = 0, ymax = Probabilidade))+ scale_x_continuous(breaks = seq(10,22,1))
dev.off()

#########Letrab 

w2 <- c(6,7,8,9,10,11,12,13,14,15,16,17,18)
pw2 <- c(("1/35"),("1/35"),("2/35"),("3/35"),("4/35"),("4/35"),("5/35"),
         "4/35","4/35","3/35","2/35","1/35","1/35")


ws <- c(6,7,8,9,10,11,12,13,14,15,16,17,18)
Probabilidade <- c((1/35),(1/35),(2/35),(3/35),(4/35),(4/35),(5/35),
         4/35,4/35,3/35,2/35,1/35,1/35)
final <- plot(ws,Probabilidade)
library(ggplot2)
jpeg("method3_test.jpg")
p <- ggplot(final, aes(ws,Probabilidade))
p + geom_linerange(aes(ymin = 0, ymax = Probabilidade)) + scale_x_continuous(breaks = seq(6,18,1))
dev.off()
  

###############Letrac
w1 <- c(10,11,12,13,14,15,16,17,18,19,20,21,22)
u <- c(w1 - 10)
ws <- c(6,7,8,9,10,11,12,13,14,15,16,17,18)
us <- c(ws - 6)



```

